package com.buildit.enums;

public enum ProductCategory {
    FRESH_PRODUCE,
    VEGETABLES,
    DAIRY_EGGS,
    SNACKS,
    COLD_DRINKS,
    PHARMACY,
    PET_CARE,
    PAAN_CORNER,
    BREAKFAST_INSTANT_FOOD,
    SWEET_TOOTH,
    BAKERY_BISCUITS,
    TEA_COFFEE_MILK_DRINKS,
    ATTA_RICE_DAL,
    MASALA_OIL_MORE,
    SAUCES_SPREADS,
    CHICKEN_MEAT_FISH,
    ORGANIC_HEALTHY_LIVING,
    BABY_CARE,
    CLEANING_ESSENTIALS,
    HOME_OFFICE,
    PERSONAL_CARE
}
