export const NEARBY_STORE_GROUPS = [
  {
    category: 'Fresh Produce & Supermarkets',
    icon: '🥦',
    stores: [
      {
        name: "Nature's Basket Express",
        location: 'Indiranagar, 100ft Road',
        distanceKm: 2.5,
        etaMinutes: 22,
        rating: 4.9,
        reviewCount: 3100,
        description: 'Premium Gourmet, Artisanal Cheese & Imported Goods',
      },
    ],
  },
  {
    category: 'Fresh Meat, Fish & Poultry',
    icon: '🥩',
    stores: [
      {
        name: 'The Meat Shop',
        location: 'HSR Layout, Sector 6',
        distanceKm: 1.5,
        etaMinutes: 15,
        rating: 4.6,
        reviewCount: 1400,
        description: 'Fresh Cut Chicken, Mutton & Seafood',
      },
      {
        name: 'Koramangala Fish & Meat Hub',
        location: 'Koramangala, 5th Block',
        distanceKm: 2.0,
        etaMinutes: 20,
        rating: 4.5,
        reviewCount: 820,
        description: 'Marine Fish, Fresh Prawns & Cold Cuts',
      },
      {
        name: "Nandu's Meat Store",
        location: 'BTM Layout, 2nd Stage',
        distanceKm: 1.8,
        etaMinutes: 18,
        rating: 4.8,
        reviewCount: 2200,
        description: 'Farm-Raised Poultry, Marinades & Ready-to-Cook',
      },
    ],
  },
  {
    category: 'Pharmacies & Healthcare',
    icon: '💊',
    stores: [
      {
        name: 'Apollo Pharmacy',
        location: 'HSR Layout, 27th Main',
        distanceKm: 0.8,
        etaMinutes: 10,
        rating: 4.9,
        reviewCount: 4500,
        description: 'Prescription Medicines, First Aid & Wellness',
      },
      {
        name: 'MedPlus Pharmacy',
        location: 'Koramangala, 4th Block',
        distanceKm: 1.4,
        etaMinutes: 14,
        rating: 4.6,
        reviewCount: 1100,
        description: 'Healthcare Supplements, OTC Drugs & Personal Care',
      },
      {
        name: 'Trust Pharmacy & Diagnostics',
        location: 'Jayanagar, 4th Block',
        distanceKm: 2.8,
        etaMinutes: 22,
        rating: 4.7,
        reviewCount: 890,
        description: 'Baby Care, Surgical Supplies & Medicines',
      },
    ],
  },
  {
    category: 'Bakery, Dairy & Confectionery',
    icon: '🍞',
    stores: [
      {
        name: "Thom's Bakery & Supermarket",
        location: 'Frazer Town',
        distanceKm: 3.5,
        etaMinutes: 25,
        rating: 4.9,
        reviewCount: 5200,
        description: 'Fresh Breads, Cakes, Pastries & European Foods',
      },
    ],
  },
  {
    category: 'Pet Care & Supplies',
    icon: '🐶',
    stores: [
      {
        name: 'Heads Up For Tails (HUFT)',
        location: 'Koramangala, 80ft Road',
        distanceKm: 1.9,
        etaMinutes: 18,
        rating: 4.9,
        reviewCount: 1600,
        description: 'Premium Dog/Cat Food, Treats, Toys & Grooming',
      },
      {
        name: 'Paws & Claws Pet Shop',
        location: 'HSR Layout, Sector 2',
        distanceKm: 1.3,
        etaMinutes: 15,
        rating: 4.7,
        reviewCount: 740,
        description: 'Pet Healthcare, Collars, Litter & Supplies',
      },
    ],
  },
  {
    category: 'Liquor Stores & Vineyards',
    icon: '🍷',
    stores: [
      {
        name: 'HSR Wine Store',
        location: 'HSR Layout, 7th Sector',
        distanceKm: 1.1,
        etaMinutes: 15,
        rating: 4.4,
        reviewCount: 1900,
        description: 'Spirits, Beer, Domestic & Imported Wines',
      },
      {
        name: 'The Booze House',
        location: 'Koramangala, 2nd Block',
        distanceKm: 2.2,
        etaMinutes: 20,
        rating: 4.5,
        reviewCount: 2400,
        description: 'Craft Beers, Liqueurs & Mixers',
      },
    ],
  },
  {
    category: 'Specialty, Pan & Gifting',
    icon: '🎁',
    stores: [
      {
        name: 'Sri Ganesh Paan & Novelty',
        location: 'HSR Layout, Sector 4',
        distanceKm: 0.6,
        etaMinutes: 10,
        rating: 4.6,
        reviewCount: 620,
        description: 'Sweet Paan, Hookah Flavors & Refreshments',
      },
      {
        name: 'FNP Flowers & Gifts',
        location: 'Indiranagar',
        distanceKm: 2.9,
        etaMinutes: 25,
        rating: 4.8,
        reviewCount: 1100,
        description: 'Fresh Flowers, Bouquet Arrangements & Chocolates',
      },
    ],
  },
]
