spring:
  application:
    name: BuildIt
  profiles:
    active: dev
server:
  port: ${PORT:8080}
jwt:
  secret: ${JWT_SECRET:superSecretKeyForJwtSigningInBuildItAppHyperlocalMarketplace}
  expiration: ${JWT_EXPIRATION:86400000}
razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}
